### ISSUE TITLE
Installation issues and instructions

### ISSUE THREAD

**Issue by SRSteinkamp** [ollie-hulme/BayesianModels#1]
## Update instructions:

* Add a few links to install miniforge3 (anaconda should not be used anymore due to licensing).

## Mac issues: 

* Current environment.yml does not seem to work out of the box on MAC
* Looks like it requires jags to be installed and pyjags is only on pip not conda-forge. 

Might also be the problem with the binder installation failing.

## ToDos

- [x] Update environment.yml (@SRSteinkamp) 
- [ ] Test on windows machine (@SRSteinkamp)
- [x] Update instructions (@ollie-hulme )

**Comment by ollie-hulme** [comment]
the main aim is for it to work on binder not on the local machine. so is linking to miniforge still necessary? the instructions are currently junk but i will write them properly shortly...

**Comment by ollie-hulme** [comment]
re updating environment. i havent really been assuming anyone else is accessing the github. so i was running notebooks locally and thus the environment is no longer relevant. if i export my current env to environment.yml its massively long which i am concerned will take ages to load on binder. i will try now but this means i will update the environment.yml

**Comment by ollie-hulme** [comment]
i have updated the environment and i am just checking it works on binder... so far so good.

**Comment by SRSteinkamp** [comment]
The environment export in conda is quite terrible, as it's exporting *all* installed packages, many which are OS specific, so it's better to keep track of the individual packages and their version at installation point. 

If you use pyjags at any point, I think I have an updated environment file, that also install jags into conda. 

But still need to test on windows.

**Comment by SRSteinkamp** [comment]
```yaml
name: bayesian-models
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - jupyterlab
  - jags # Jags installation
  - pkg-config # pkg-config for pyjags installation
  - numpy=1.24
  - pip:
    - matplotlib==3.7
    - scipy==1.10
    - ipywidgets==8.0
    - seaborn
    - ipympl               # for `%matplotlib ipympl` to work
    - pyjags
```
